create table if not exists product_reviews (
    review_id text primary key,
    product_name text,
    brand text,
    category text,
    rating numeric,
    price numeric,
    review_title text,
    review_text text,
    review_date date,
    feature_tags text[],
    sentiment_label text,
    created_at timestamp default now()
);

create table if not exists ai_insights (
    insight_id bigint generated by default as identity primary key,
    category text,
    brand text,
    question text,
    answer text,
    source_review_ids text[],
    created_at timestamp default now()
);
